server:
  port: 8008
  servlet:
    session:
      timeout: 15m # session 会话超时时间 默认30 分钟（m） 最小一分钟
      cookie:
        name: JSESSIONID # 指定浏览器 cookie 中关于sessionId 保存的名称
spring:
  thymeleaf:
    cache: false #关闭 thymeleaf 缓存
  datasource:
    username: root
    password: Mysql147.@
    url: jdbc:mysql://49.235.27.226:3339/study-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis # session  的存储方式
  redis:
    host: 49.235.27.226
    port: 6379
    password: Redis123.

haidman:
  security:
    authentication:
      loginPage: /login/page #响应认证的url(登录页面)
      loginProcessingUrl: /login/token # 登录表单提交处理的url, 默认为 /login
      usernameParameter: author # 默认为 username
      passwordParameter: authorCode # 默认为 password
      staticPaths: # 静态资源路径
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT #请求认证成功后响应类型
#      "/code/image", "/mobile/page", "/code/mobile"
      imageCodeUrl: /code/image #获取图形验证码url
      mobileCodeUrl: /code/mobile #获取手机验证码url
      mobilePageUrl: /mobile/page #跳转手机登录页面url
      tokenValiditySeconds: 259200 # 记住我功能 时常 3 天  60*60*24*3