server:
  port: 8008
spring:
  thymeleaf:
    cache: false #关闭 thymeleaf 缓存
  datasource:
    username: root
    password: Mysql147.@
    url: jdbc:mysql://49.235.27.226:3339/study-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

haidman:
  security:
    authentication:
      loginPage: /login/page #响应认证的url(登录页面)
      loginProcessingUrl: /login/token # 登录表单提交处理的url, 默认为 /login
      usernameParameter: author # 默认为 username
      passwordParameter: authorCode # 默认为 password
      staticPaths: # 静态资源路径
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT #请求认证成功后响应类型