server:
  port: 80
spring:
  thymeleaf:
    cache: false #关闭 thymeleaf 缓存

haidman:
  security:
    authentication:
      loginPage: /login/page #响应认证的url(登录页面)
      loginProcessingUrl: /login/token # 登录表单提交处理的url, 默认为 /login
      usernameParameter: author # 默认为 username
      passwordParameter: authorCode # 默认为 password
      staticPaths: # 静态资源路径
        - /dist/**
        - /modules/**
        - /plugins/**